[package]
name = "lowpassns"
version = "0.2.0"
edition = "2021"
authors = ["Jorge Andre Castro <georgeandrec@gmail.com>"]
license = "GPL-2.0-or-later"
description = "Lightweight no_std low-pass filters for embedded systems, open source and GPL-protected."
repository = "https://github.com/jorgeandrecastro/lowpassns"
documentation = "https://docs.rs/lowpassns"
readme = "Readme.md"

[profile.release]
opt-level = 3      # Optimize for speed
lto = true           # Link Time Optimization (dead code elimination)
codegen-units = 1    # Maximize optimization at expense of compile time
panic = "abort"      # Removes heavy error messages on crash
strip = true         # Strips all debug symbols

[features]
# By default, f64 is used for precision
default = [] 
# f32 option for memory-constrained MCUs
f32 = []

[badges]
maintenance = { status = "actively-developed" }